//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace genkPrint_v0._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public int AgetId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string NIRC { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
