//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenkPrintMVC_v0._5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditTransLog
    {
        public int TrnsId { get; set; }
        public int CurrId { get; set; }
        public Nullable<decimal> CurrCredit { get; set; }
        public Nullable<decimal> DeductCredit { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
    
        public virtual CurrCreditAmount CurrCreditAmount { get; set; }
    }
}
