//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenkPrintMVC_v0._5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsubCategory
    {
        public int ProductsubCatId { get; set; }
        public Nullable<int> ProductCatId { get; set; }
        public string ProductsubCatCode { get; set; }
        public string ProductsubCatName { get; set; }
        public string ProductsubCatDesc { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
